// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución: 12.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using Polizas.Entities;
using Polizas.Entities.Clientes;
using Polizas.Entities.Expedientes;
using Polizas.Entities.Juzgados;
using Polizas.Entities.Roles;
using Polizas.Entities.Ubicacion;
using Polizas.Entities.Usuarios;

namespace Polizas.Data.Model
{
    public sealed class PolizasModelContextBase : ObjectContext
    {
        private readonly EntityConnection _connection;
        private readonly string _connectionString;
        private const string ConnectionString = "name=PolizasEntities";
        private const string ContainerName = "PolizasEntities";

        public PolizasModelContextBase()
            : base(ConnectionString, ContainerName)
        {
            try
            {
                _audiencia = CreateObjectSet<Audiencia>();
                _caso = CreateObjectSet<Caso>();
                _cita = CreateObjectSet<Cita>();
                _cliente = CreateObjectSet<Cliente>();
                _clienteDireccion = CreateObjectSet<ClienteDireccion>();
                _clienteTelefono = CreateObjectSet<ClienteTelefono>();
                _colonia = CreateObjectSet<Colonia>();
                _estado = CreateObjectSet<Estado>();
                _juzgado = CreateObjectSet<Juzgado>();
                _juzgadoDireccion = CreateObjectSet<JuzgadoDireccion>();
                _juzgadoTelefono = CreateObjectSet<JuzgadoTelefono>();
                _municipio = CreateObjectSet<Municipio>();
                _pais = CreateObjectSet<Pais>();
                _pantalla = CreateObjectSet<Pantalla>();
                _puesto = CreateObjectSet<Puesto>();
                _rol = CreateObjectSet<Rol>();
                _rolPantalla = CreateObjectSet<RolPantalla>();
                _tipoCaso = CreateObjectSet<TipoCaso>();
                _tipoTelefono = CreateObjectSet<TipoTelefono>();
                _usuario = CreateObjectSet<Usuario>();
                _usuarioDireccion = CreateObjectSet<UsuarioDireccion>();
                _usuarioRol = CreateObjectSet<UsuarioRol>();
                _usuarioTelefono = CreateObjectSet<UsuarioTelefono>();
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }


        }

        public PolizasModelContextBase(string connectionString)
            : base(ConnectionString, ContainerName)
        {
            _connectionString = connectionString;
        }

        public PolizasModelContextBase(EntityConnection connection)
            : base(ConnectionString, ContainerName)
        {
            _connection = connection;
        }

        private readonly ObjectSet<Audiencia> _audiencia;
        private readonly ObjectSet<Caso> _caso;
        private readonly ObjectSet<Cita> _cita;
        private readonly ObjectSet<Cliente> _cliente;
        private readonly ObjectSet<ClienteDireccion> _clienteDireccion;
        private readonly ObjectSet<ClienteTelefono> _clienteTelefono;
        private readonly ObjectSet<Colonia> _colonia;
        private readonly ObjectSet<Estado> _estado;
        private readonly ObjectSet<Juzgado> _juzgado;
        private readonly ObjectSet<JuzgadoDireccion> _juzgadoDireccion;
        private readonly ObjectSet<JuzgadoTelefono> _juzgadoTelefono;
        private readonly ObjectSet<Municipio> _municipio;
        private readonly ObjectSet<Pais> _pais;
        private readonly ObjectSet<Pantalla> _pantalla;
        private readonly ObjectSet<Puesto> _puesto;
        private readonly ObjectSet<Rol> _rol;
        private readonly ObjectSet<RolPantalla> _rolPantalla;
        private readonly ObjectSet<TipoCaso> _tipoCaso;
        private readonly ObjectSet<TipoTelefono> _tipoTelefono;
        private readonly ObjectSet<Usuario> _usuario;
        private readonly ObjectSet<UsuarioDireccion> _usuarioDireccion;
        private readonly ObjectSet<UsuarioRol> _usuarioRol;
        private readonly ObjectSet<UsuarioTelefono> _usuarioTelefono;

        public ObjectSet<Audiencia> Audiencia
        {
            get { return _audiencia; }
        }

        public ObjectSet<Caso> Caso
        {
            get { return _caso; }
        }

        public ObjectSet<Cita> Cita
        {
            get { return _cita; }
        }

        public ObjectSet<Cliente> Cliente
        {
            get { return _cliente; }
        }

        public ObjectSet<ClienteDireccion> ClienteDireccion
        {
            get { return _clienteDireccion; }
        }

        public ObjectSet<ClienteTelefono> ClienteTelefono
        {
            get { return _clienteTelefono; }
        }

        public ObjectSet<Colonia> Colonia
        {
            get { return _colonia; }
        }

        public ObjectSet<Estado> Estado
        {
            get { return _estado; }
        }

        public ObjectSet<Juzgado> Juzgado
        {
            get { return _juzgado; }
        }

        public ObjectSet<JuzgadoDireccion> JuzgadoDireccion
        {
            get { return _juzgadoDireccion; }
        }

        public ObjectSet<JuzgadoTelefono> JuzgadoTelefono
        {
            get { return _juzgadoTelefono; }
        }

        public ObjectSet<Municipio> Municipio
        {
            get { return _municipio; }
        }

        public ObjectSet<Pais> Pais
        {
            get { return _pais; }
        }

        public ObjectSet<Pantalla> Pantalla
        {
            get { return _pantalla; }
        }

        public ObjectSet<Puesto> Puesto
        {
            get { return _puesto; }
        }

        public ObjectSet<Rol> Rol
        {
            get { return _rol; }
        }

        public ObjectSet<RolPantalla> RolPantalla
        {
            get { return _rolPantalla; }
        }

        public ObjectSet<TipoCaso> TipoCaso
        {
            get { return _tipoCaso; }
        }

        public ObjectSet<TipoTelefono> TipoTelefono
        {
            get { return _tipoTelefono; }
        }

        public ObjectSet<Usuario> Usuario
        {
            get { return _usuario; }
        }

        public ObjectSet<UsuarioDireccion> UsuarioDireccion
        {
            get { return _usuarioDireccion; }
        }

        public ObjectSet<UsuarioRol> UsuarioRol
        {
            get { return _usuarioRol; }
        }

        public ObjectSet<UsuarioTelefono> UsuarioTelefono
        {
            get { return _usuarioTelefono; }
        }
    }
}
